# Generated by Django 5.0 on 2023-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
            ],
            options={
                'verbose_name': 'Запросы на связи',
                'verbose_name_plural': 'Запросы на связь',
            },
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('date', models.CharField(max_length=255, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Брони',
                'verbose_name_plural': 'Бронь',
            },
        ),
    ]
