# Generated by Django 5.0 on 2023-12-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
