# Generated by Django 5.0 on 2023-12-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('data', models.CharField(max_length=255, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запрос на связь',
                'verbose_name_plural': 'Запросы на связь',
            },
        ),
        migrations.CreateModel(
            name='PageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Дата')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Соощении',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Reserv',
        ),
    ]
