# Generated by Django 5.0 on 2023-12-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_settings_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='admin_token',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='telegram_token',
        ),
    ]
